---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
    user_name: marc2029
    group_name: devops
  vars_files:
    - variables.yml
  tasks:
    - name: Check the time
      command: dateabwnw
 #     when: ansible_distribution == "marc" or ansible_processor_nproc == 2
    - name: Create user Marc
      user:
        name: "{{user_name}}"
        comment: Marc Admin
        state: present
    - name: Create group
      group:
        name: "{{group_name}}"
        state: present
    - name: Install package
      package: 
        name: "{{pkg_name}}"
        state: present